workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "TravelExpenses.xcodeproj"
        XCODE_SCHEME: "TravelExpenses"
        BUNDLE_ID: "com.Travon.TravelExpenses"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
        CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
        CERTIFICATE_PASSWORD: $CERTIFICATE_PASSWORD
        BUILD_CERTIFICATE_BASE64: $BUILD_CERTIFICATE_BASE64
        KEYCHAIN_PASSWORD: $KEYCHAIN_PASSWORD
        PROVISIONING_PROFILE_BASE64: $PROVISIONING_PROFILE_BASE64
        PROVISIONING_PROFILE_SPECIFIER: $PROVISIONING_PROFILE_SPECIFIER
        TEAM_ID: "74335G6GZ5"
        CODE_SIGN_IDENTITY: $CODE_SIGN_IDENTITY
      flutter: stable
      node: latest
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          # update project settings with correct object IDs
          # Debug configuration
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C82E212CD800C7DB37:buildSettings:CODE_SIGN_STYLE Automatic" "$XCODE_PROJECT/project.pbxproj"
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C82E212CD800C7DB37:buildSettings:DEVELOPMENT_TEAM 74335G6GZ5" "$XCODE_PROJECT/project.pbxproj"
          
          # Release configuration
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C92E212CD800C7DB37:buildSettings:CODE_SIGN_STYLE Automatic" "$XCODE_PROJECT/project.pbxproj"
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C92E212CD800C7DB37:buildSettings:DEVELOPMENT_TEAM 74335G6GZ5" "$XCODE_PROJECT/project.pbxproj"
      - name: Get iOS code signing files
        script: |
          # Install fastlane
          gem install fastlane
          
          # Set up keychain for code signing
          security create-keychain -p "codemagic" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "codemagic" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
          
          # Set partition list
          security set-key-partition-list -S apple-tool:,apple: -s -k "codemagic" build.keychain
          
          # Create API key file manually
          cat > /tmp/api_key.json << EOF
          {
            "keyId": "$APP_STORE_CONNECT_API_KEY_ID",
            "issuerId": "$APP_STORE_CONNECT_ISSUER_ID",
            "privateKey": "$APP_STORE_CONNECT_API_KEY"
          }
          EOF
          
          # Create export options plist early
          cat > /tmp/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>74335G6GZ5</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          # Create App Store Connect credentials file
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8
          
          # Set environment variables for App Store Connect
          export APP_STORE_CONNECT_ISSUER_ID="$APP_STORE_CONNECT_ISSUER_ID"
          export APP_STORE_CONNECT_API_KEY_ID="$APP_STORE_CONNECT_API_KEY_ID"
          export APP_STORE_CONNECT_API_KEY_PATH="~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_API_KEY_ID.p8"
          
          # Use fastlane to sync certificates and profiles
          fastlane run sync_code_signing \
            type:appstore \
            app_identifier:com.Travon.TravelExpenses \
            team_id:74335G6GZ5 \
            api_key_path:/tmp/api_key.json \
            readonly:false || echo "Fastlane sync completed"
      - name: Build iOS app
        script: |
          # Set App Store Connect environment variables
          export APP_STORE_CONNECT_ISSUER_ID="$APP_STORE_CONNECT_ISSUER_ID"
          export APP_STORE_CONNECT_API_KEY_ID="$APP_STORE_CONNECT_API_KEY_ID"
          export APP_STORE_CONNECT_API_KEY="$APP_STORE_CONNECT_API_KEY"
          
          # Build the app with automatic provisioning updates and App Store Connect credentials
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath /tmp/build/TravelExpenses.xcarchive \
            -allowProvisioningUpdates \
            -allowProvisioningDeviceRegistration \
            clean archive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=74335G6GZ5 \
            PRODUCT_BUNDLE_IDENTIFIER=com.Travon.TravelExpenses
      - name: Create iOS build artifacts
        script: |
          # Create .ipa file with automatic provisioning updates
          xcodebuild -exportArchive \
            -archivePath /tmp/build/TravelExpenses.xcarchive \
            -exportPath /tmp/build/ios \
            -exportOptionsPlist /tmp/exportOptions.plist \
            -allowProvisioningUpdates
      - name: Publish to App Store Connect
        script: |
          # Upload to App Store Connect using xcrun notarytool
          echo "Uploading to App Store Connect..."
          xcrun notarytool submit "/tmp/build/ios/TravelExpenses.ipa" \
            --apple-id "$APP_STORE_CONNECT_USERNAME" \
            --password "$APP_STORE_CONNECT_APP_SPECIFIC_PASSWORD" \
            --team-id "74335G6GZ5" \
            --wait
    artifacts:
      - /tmp/build/ios/*.ipa
      - /tmp/build/TravelExpenses.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false 