workflows:
  ios-workflow:
    integrations:
      app_store_connect: TravelExpensesCodemagic
    environment:
      groups:
        - vars
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "TravelExpenses.xcodeproj"
        XCODE_SCHEME: "TravelExpenses"
        BUNDLE_ID: "com.Travon.TravelExpenses"
        TEAM_ID: "74335G6GZ5"
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
      flutter: stable
      node: latest
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C82E212CD800C7DB37:buildSettings:CODE_SIGN_STYLE Automatic" "$XCODE_PROJECT/project.pbxproj"
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C82E212CD800C7DB37:buildSettings:DEVELOPMENT_TEAM $TEAM_ID" "$XCODE_PROJECT/project.pbxproj"
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C92E212CD800C7DB37:buildSettings:CODE_SIGN_STYLE Automatic" "$XCODE_PROJECT/project.pbxproj"
          /usr/libexec/PlistBuddy -c "Set :objects:F21C12C92E212CD800C7DB37:buildSettings:DEVELOPMENT_TEAM $TEAM_ID" "$XCODE_PROJECT/project.pbxproj"
          echo "✅ Code signing settings updated"
      - name: Create export options plist
        script: |
          cat > /tmp/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          echo "✅ Export options plist created"
      - name: Build iOS app
        script: |
          echo "Building iOS app..."
          mkdir -p /tmp/build
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath "/tmp/build/TravelExpenses.xcarchive" \
            -allowProvisioningUpdates \
            clean archive
          if [ ! -d "/tmp/build/TravelExpenses.xcarchive" ]; then
            echo "❌ Archive not created"
            exit 1
          fi
          echo "✅ Archive created successfully"
          xcodebuild -exportArchive \
            -archivePath "/tmp/build/TravelExpenses.xcarchive" \
            -exportPath "/tmp/build/ios" \
            -exportOptionsPlist /tmp/exportOptions.plist
          if [ ! -f "/tmp/build/ios/TravelExpenses.ipa" ]; then
            echo "❌ IPA not created"
            exit 1
          fi
          echo "✅ iOS app built successfully"
      - name: Create iOS build artifacts
        script: |
          echo "Checking for created artifacts..."
          ls -la /tmp/build/ios/
          if [ -f "/tmp/build/ios/TravelExpenses.ipa" ]; then
            echo "✅ TravelExpenses.ipa created successfully"
          else
            echo "❌ TravelExpenses.ipa not found"
            exit 1
          fi
    artifacts:
      - /tmp/build/ios/*.ipa
      - /tmp/build/TravelExpenses.xcarchive
    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false 